repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  braincheck: org.realityforge.braincheck:braincheck-core:jar:1.30.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  akasha: org.realityforge.akasha:akasha-java:jar:0.05

  javax_json: org.glassfish:javax.json:jar:1.1

  autoservice: com.google.auto.service:auto-service:jar:1.0-rc3
  autocommon: com.google.auto:auto-common:jar:0.10
  javapoet: com.squareup:javapoet:jar:1.13.0
  guava: com.google.guava:guava:jar:27.1-jre
  guava_failureaccess: com.google.guava:failureaccess:jar:1.0.1

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.18-rf
  truth: com.google.truth:truth:jar:0.45
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3
  errorprone: com.google.errorprone:javac-shaded:jar:9-dev-r4023-3
  error_prone_annotations: com.google.errorprone:error_prone_annotations:jar:2.0.15

  gir: org.realityforge.gir:gir-core:jar:0.11

  jdepend: guru.nidi:jdepend:jar:2.9.5

  gwt_symbolmap: org.realityforge.gwt.symbolmap:gwt-symbolmap:jar:0.09

  zemeckis: org.realityforge.zemeckis:zemeckis-core:jar:0.09
  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.05
